<img src="https://github.com/azvicer-a11y/DSB-Unit-03/blob/main/labs/02%20-%20Classification-LeftHanded/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Lab: Classification: Predicting Left-Handedness from Psychological Factors

---

One way to define the data science process is as follows:

1. Define the problem.
2. Obtain the data.
3. Explore the data.
4. Model the data.
5. Evaluate the model.
6. Answer the problem.

We'll walk through a full data science problem in this lab.

---
## Step 1: Define The Problem.

You're currently a data scientist working at a university. A professor of psychology is attempting to study the relationship between personalities and left-handedness. They have tasked you with gathering evidence so that they may publish.

As a data scientist, you know that any real data science problem must be **specific** and **conclusively answerable**. For example:
- Bad data science problem: "What is the link between obesity and blood pressure?"
    - This is vague and is not conclusively answerable. That is, two people might look at the conclusion and one may say "Sure, the problem has been answered!" and the other may say "The problem has not yet been answered."
- Good data science problem: "Does an association exist between obesity and blood pressure?"
    - This is more specific and is conclusively answerable. The problem specifically is asking for a "Yes" or "No" answer. Based on that, two independent people should both be able to say either "Yes, the problem has been answered" or "No, the problem has not yet been answered."
- Excellent data science problem: "As obesity increases, how does blood pressure change?"
    - This is very specific and is conclusively answerable. The problem specifically seeks to understand the effect of one variable on the other.

### In the context of the left-handedness and personality example, what are three specific and conclusively answerable problems that you could answer using data science?

> You might find it helpful to check out the codebook in the repo for some inspiration.

---
## Step 2: Obtain the data.

### Read in the file titled "data.csv":
> Hint: Despite being saved as a .csv file, you won't be able to simply `pd.read_csv()` this data!

In [ ]:
# library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn import metrics

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

In [5]:
lh_df = pd.read_csv('https://raw.githubusercontent.com/azvicer-a11y/DSB-Unit-03/refs/heads/main/labs/02%20-%20Classification-LeftHanded/data/data.csv', sep="\t")

In [6]:
lh_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   object
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), object(1)
memory usage: 1.8+ MB

---

## Step 3: Explore the data.

### Conduct background research:

Domain knowledge is irreplaceable. Figuring out what information is relevant to a problem, or what data would be useful to gather, is a major part of any end-to-end data science project! For this lab, you'll be using a dataset that someone else has put together, rather than collecting the data yourself.

Do some background research about personality and handedness. What features, if any, are likely to help you make good predictions? How well do you think you'll be able to model this? Write a few bullet points summarizing what you believe, and remember to cite external sources.

You don't have to be exhaustive here. Do enough research to form an opinion, and then move on.

> You'll be using the answers to Q1-Q44 for modeling; you can disregard other features, e.g. country, age, internet browser.

### Conduct exploratory data analysis on this dataset:

If you haven't already, be sure to check out the codebook in the repo, as that will help in your EDA process.

You might use this section to perform data cleaning if you find it to be necessary.

In [7]:
lh_df.head(10)

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3
5,5,4,2,2,1,1,3,3,3,1,...,US,2,1,59,4,1,1,6,7,1
6,3,4,4,4,1,4,3,5,5,4,...,GR,2,2,15,2,2,1,6,1,1
7,1,2,1,1,1,4,1,2,5,3,...,GR,2,2,14,1,2,0,6,1,1
8,1,5,1,2,2,4,3,2,2,3,...,GR,2,2,16,2,2,0,6,2,1
9,1,4,3,1,1,3,5,2,2,5,...,US,2,2,15,2,3,5,6,1,2

In [8]:
lh_df.tail(10)

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
4174,1,5,3,4,5,4,3,2,1,5,...,US,2,1,17,2,3,4,6,1,1
4175,1,4,1,1,4,5,4,3,1,4,...,EG,2,1,21,4,1,3,6,1,1
4176,1,1,5,5,1,5,5,3,5,5,...,PL,2,2,17,1,1,3,6,2,1
4177,1,3,4,3,3,5,5,2,1,5,...,IE,1,1,51,2,2,4,6,2,1
4178,1,2,1,1,3,4,4,1,1,2,...,US,1,1,25,3,1,2,6,1,1
4179,3,5,4,5,2,4,2,2,2,5,...,US,1,1,18,2,1,1,6,2,1
4180,1,5,1,5,1,4,2,4,1,4,...,US,1,1,18,2,2,1,3,2,1
4181,3,2,2,4,5,4,5,2,2,5,...,PL,2,2,22,2,1,1,6,1,1
4182,1,3,4,5,1,3,3,1,1,3,...,US,2,1,16,1,2,5,1,1,1
4183,2,5,3,3,5,3,4,3,1,5,...,NZ,2,1,22,3,2,4,6,1,1

### Calculate and interpret the baseline accuracy rate:

In [9]:
lh_df.describe()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,...,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000
mean,1.962715,3.829589,2.846558,3.186902,2.865440,3.672084,3.216539,3.184512,2.761233,3.522945,...,479.994503,1.576243,1.239962,30.370698,2.317878,1.654398,1.833413,5.013623,2.394359,1.190966
std,1.360291,1.551683,1.664804,1.476879,1.545798,1.342238,1.490733,1.387382,1.511805,1.242890,...,3142.178542,0.494212,0.440882,367.201726,0.874264,0.640915,1.303454,1.970996,2.184164,0.495357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.000000,1.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,...,186.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,5.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,...,242.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,...,324.250000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,119834.000000,2.000000,2.000000,23763.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

In [11]:
lh_df.head(10).transpose()

               0    1     2     3    4    5    6    7    8    9
Q1             4    1     1     1    5    5    3    1    1    1
Q2             1    5     2     4    1    4    4    2    5    4
Q3             5    1     1     1    5    2    4    1    1    3
Q4             1    4     1     5    1    2    4    1    2    1
Q5             5    2     5     1    5    1    1    1    2    1
Q6             1    5     4     4    1    1    4    4    4    3
Q7             5    5     3     5    5    3    3    1    3    5
Q8             1    4     2     4    1    3    5    2    2    2
Q9             4    1     1     3    3    3    5    5    2    2
Q10            1    5     4     5    1    1    4    3    3    5
Q11            1    2     4     1    1    1    5    5    3    3
Q12            1    5     5     3    1    2    1    1    3    3
Q13            5    3     4     2    5    2    3    3    1    1
Q14            5    4     3     3    5    2    3    1    2    2
Q15            5    1     4     1    5    3    5    5    3    1
Q16            1    4     1     5    1    1    1    1    3    3
Q17            5    1     2     2    5    1    2    2    3    0
Q18            1    1     3     2    1    2    4    4    4    4
Q19            5    1     1     5    5    5    5    5    3    5
Q20            1    5     3     5    2    1    5    2    3    5
Q21            5    2     3     2    5    2    2    4    3    5
Q22            1    4     3     3    1    5    4    3    4    5
Q23            1    4     4     2    5    4    5    4    2    4
Q24            1    4     5     2    1    2    5    1    3    5
Q25            5    1     3     1    5    4    2    1    2    5
Q26            5    2     2     4    5    4    1    1    3    2
Q27            5    1     2     1    5    5    4    3    1    1
Q28            1    2     2     1    1    1    1    1    1    1
Q29            5    1     1     1    5    5    1    2    1    5
Q30            1    3     4     3    1    5    1    1    3    1
Q31            1    1     3     4    5    2    5    2    1    4
Q32            1    5     3     1    1    1    2    1    2    5
Q33            1    2     4     3    5    2    5    5    1    5
Q34            5    4     4     5    5    1    3    3    3    4
Q35            5    4     2     5    5    5    3    1    1    5
Q36            1    4     2     1    1    5    1    1    4    1
Q37            1    4     4     3    1    2    4    3    2    5
Q38            1    4     2     4    1    2    1    1    3    1
Q39            5    1     1     1    5    5    1    2    1    3
Q40            5    3     4     2    5    4    2    1    5    2
Q41            5    1     2     1    5    5    5    3    3    4
Q42            1    4     2     1    1    5    4    1    2    1
Q43            5    4     2     1    5    5    4    3    1    1
Q44            1    5     2     3    1    1    2    1    5    2
introelapse   91   17    11    14   10   54    9  395   20   23
testelapse   232  247  6774  1072  226  372  452  674  509  358
country       US   CA    NL    US   US   US   GR   GR   GR   US
fromgoogle     2    2     2     2    2    2    2    2    2    2
engnat         1    1     2     1    1    1    2    2    2    2
age           22   14    30    18   22   59   15   14   16   15
education      3    1     4     2    3    4    2    1    2    2
gender         1    2     1     2    1    1    2    2    2    3
orientation    1    2     1     5    1    1    1    0    0    5
race           3    6     1     3    3    6    6    6    6    6
religion       2    1     1     2    2    7    1    1    2    1
hand           3    1     2     2    3    1    1    1    1    2

In [24]:
lh_df['age'].max()

23763

In [25]:
lh_df[lh_df['age']>100]

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
2075,3,4,5,4,3,4,5,4,3,3,...,US,2,1,123,1,1,5,7,7,3
2137,1,2,5,4,3,1,5,1,5,3,...,US,2,1,409,2,1,5,6,1,1
2690,2,5,5,1,5,5,5,5,4,2,...,US,2,2,23763,4,1,2,7,7,0

In [33]:
age_filter = lh_df['age'] < 100

filtered_df = lh_df[age_filter]

filtered_df.describe()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,...,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000,4181.000000
mean,1.962688,3.829706,2.845013,3.187037,2.864865,3.672327,3.215260,3.184406,2.760344,3.523559,...,480.141593,1.575939,1.239895,24.581679,2.317867,1.654867,1.831858,5.012437,2.392490,1.190863
std,1.360602,1.551874,1.664401,1.476915,1.545997,1.341916,1.490502,1.387127,1.511825,1.243060,...,3143.300111,0.494259,0.440852,10.869709,0.873939,0.640905,1.302078,1.971165,2.182517,0.494392
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.000000,1.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,...,186.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,5.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,...,242.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,...,324.000000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,119834.000000,2.000000,2.000000,86.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

In [34]:
left_cleaned = filtered_df[(filtered_df != 0).all(axis=1)]

In [40]:
left_cleaned.describe()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,...,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000
mean,1.977005,3.845070,2.861742,3.207531,2.892498,3.693590,3.235412,3.202357,2.768037,3.510204,...,452.526588,1.574303,1.247485,24.586088,2.360736,1.688416,1.886462,5.089968,2.500431,1.189135
std,1.371500,1.539353,1.664370,1.467313,1.544974,1.331419,1.479610,1.380629,1.504240,1.233679,...,2673.702187,0.494519,0.431613,10.580152,0.837635,0.604812,1.277504,1.878026,2.171073,0.487789
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,41.000000,1.000000,1.000000,13.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,...,185.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,6.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,...,240.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,...,323.000000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,93888.000000,2.000000,2.000000,86.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

In [42]:
lh_df.columns.tolist()

['Q1',
 'Q2',
 'Q3',
 'Q4',
 'Q5',
 'Q6',
 'Q7',
 'Q8',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q17',
 'Q18',
 'Q19',
 'Q20',
 'Q21',
 'Q22',
 'Q23',
 'Q24',
 'Q25',
 'Q26',
 'Q27',
 'Q28',
 'Q29',
 'Q30',
 'Q31',
 'Q32',
 'Q33',
 'Q34',
 'Q35',
 'Q36',
 'Q37',
 'Q38',
 'Q39',
 'Q40',
 'Q41',
 'Q42',
 'Q43',
 'Q44',
 'introelapse',
 'testelapse',
 'country',
 'fromgoogle',
 'engnat',
 'age',
 'education',
 'gender',
 'orientation',
 'race',
 'religion',
 'hand']

In [45]:
target = lh_df['hand']

baseline_accuracy = target.value_counts(normalize=True).max()

print("Baseline accuracy:", baseline_accuracy)
print("Baseline percentage:", baseline_accuracy * 100, "%")

Baseline accuracy: 0.8465583173996176
Baseline percentage: 84.65583173996177 %

### Short answer questions:

In this lab you'll use K-nearest neighbors and logistic regression to model
handedness based off of psychological factors.

Answer the following related questions; your answers may be in bullet points
**on your own words**

#### Describe the difference between regression and classification problems:

In [ ]:
#Classification problem is such as

#### Considering $k$-nearest neighbors, describe the relationship between $k$ and the bias-variance tradeoff:

#### Why do we often standardize predictor variables when using $k$-nearest neighbors?

#### Do you think we should standardize the explanatory variables for this problem? Why or why not?

#### How do we settle on $k$ for a $k$-nearest neighbors model?

#### What is the default type of regularization for logistic regression as implemented in scikit-learn? (You might [check the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).)

#### [Bonus - Optional] Describe the relationship between the scikit-learn `LogisticRegression` argument `C` and regularization strength:

#### Describe the relationship between regularization strength and the bias-variance tradeoff:

#### Logistic regression is considered more interpretable than $k$-nearest neighbors. Explain why.

---

## Step 4 & 5 Modeling: $k$-nearest neighbors

### Train-test split your data:

Your explanatory variables should be all Q columns.

NameError: name 'data' is not defined

### Create and fit four separate $k$-nearest neighbors models:

### Model 1: one with $k = 3$:

#### Model 2: one with $k = 5$

#### Model 3: one with $k = 15$

#### Model 4: one with $k = 25$:

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

---

## Step 4 & 5 Modeling: logistic regression

### Create and fit four separate logistic regression models:

*(Hint: Be careful with how you specify $\alpha$ in your model!)*
Note: You can use the same train and test data as above.

#### Model 1 : one with LASSO and $\alpha = 1$

#### Model 2 : one with LASSO and $\alpha = 10$

#### Model 3 : one with RIDGE and $\alpha = 1$

#### Model 4 : one with RIDGE and $\alpha = 10$

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

---

## Step 6: Answer the problem.

Are any of your models worth moving forward with? What are the "best" models?